set ANKI_ADDONS_PATH=%APPDATA%\Anki2\addons21
set ANKI_MASSIMPORT_ADDON_PATH=%ANKI_ADDONS_PATH%\massimport
set ANKI_MASSIMPORT_ADDON_META_JSON_PATH=%ANKI_MASSIMPORT_ADDON_PATH%\meta.json
set ANKI_MASSIMPORT_ADDON_META_JSON_BACKUP_PATH=%ANKI_ADDONS_PATH%\massimport_meta.json.bak
move /y %ANKI_MASSIMPORT_ADDON_META_JSON_PATH% %ANKI_MASSIMPORT_ADDON_META_JSON_BACKUP_PATH%
del /f /s /q %ANKI_MASSIMPORT_ADDON_PATH%
mkdir %ANKI_MASSIMPORT_ADDON_PATH%
move %ANKI_MASSIMPORT_ADDON_META_JSON_BACKUP_PATH% %ANKI_MASSIMPORT_ADDON_META_JSON_PATH%
copy src\massimport\*.* %ANKI_MASSIMPORT_ADDON_PATH%