set ANKI_ADDONS_PATH=%APPDATA%\Anki2\addons21
set ANKI_CSVIMPORT_ADDON_PATH=%ANKI_ADDONS_PATH%\csvimport
set ANKI_CSVIMPORT_ADDON_META_JSON_PATH=%ANKI_CSVIMPORT_ADDON_PATH%\meta.json
set ANKI_CSVIMPORT_ADDON_META_JSON_BACKUP_PATH=%ANKI_ADDONS_PATH%\csvimport_meta.json.bak
move /y %ANKI_CSVIMPORT_ADDON_META_JSON_PATH% %ANKI_CSVIMPORT_ADDON_META_JSON_BACKUP_PATH%
del /f /s /q %ANKI_CSVIMPORT_ADDON_PATH%
mkdir %ANKI_CSVIMPORT_ADDON_PATH%
move %ANKI_CSVIMPORT_ADDON_META_JSON_BACKUP_PATH% %ANKI_CSVIMPORT_ADDON_META_JSON_PATH%
copy src\csvimport\*.* %ANKI_CSVIMPORT_ADDON_PATH%